name: Mirror to Bitbucket Repo

on: 
    workflow_dispatch:
    schedule:
    - cron: '1 * * * *'

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@gitee.com:lxk0301/jd_scripts.git"
          destination-repo: "https://likeu99:${{ secrets.PASSWORD }}@github.com/likeu99/jd_scripts.git"
